- name: Deploy AWS EC2
  hosts: localhost
  connection: local
  gather_facts: false
  become: true

  tasks: 
    - name: start an instance with a primary and secondary network interfaces
      amazon.aws.ec2_instance:
        name: "{{ instance_name }}"
        key_name: "aap"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        instance_type: t2.micro
        image_id: "{{ image_id }}"
        region: us-east-2
        security_group: sg-020fd8404a41d6d01
        network_interfaces:
          - assign_public_ip: true
            subnet_id: subnet-06fb85a5fd9aeb398
        tags:
          foo: bar